import { useEffect, useState, useContext } from "react";
import Head from 'next/head'
import Navbar from '../components/Navbar'
import AnimalsResults from '../components/AnimalsResults'
import NotFound from '../components/NotFound'
import { AuthContext } from "./_app";
import { BrowserRouter as Router, Switch, Route, Routes} from "react-router-dom";

export default function Home() {
  const [results, setResults] = useState(null);
  const accessToken = useContext(AuthContext);
  useEffect(() => {
    if (accessToken === null) return;
    const fetchPets = async () => {
      const petResults = await fetch(
        "https://api.petfinder.com/v2/animals",
        {
          headers: {
            Authorization: `Bearer ${accessToken}`,
          },
        }
      );
      const json = await petResults.json();
      setResults(json.animals);
    };
    fetchPets();
  }, [accessToken]);
  if (results === null) return null;
  return(
     <div>

      <Head>
        <title>AdoptMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <AnimalsResults results={results} />

      {/* / => AnimalsResults results={results}
      /dogs => AnimalsResults results={+type=dogs}
      /cats => .... cats
      ...
      * => NotFound */}


    </div>
  );
};
