import Head from 'next/head'
import Navbar from '../components/Navbar'
import AllAnimals from '../components/AllAnimals'
import AnimalDetails from  '../components/AnimalDetails'

export default function Home() {
  return (
    <div>
      <Head>
        <title>AdoptMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <Navbar />

      {/* All Animals */}
      {/* <AllAnimals /> */}

      {/* Details */}
      {/* <AnimalDetails /> */}

    </div>
  )
}
